### PR TITLE
Implement wireframe

### PR DESCRIPTION
**Pull request by vitorbaptista**

### CODE REVIEW

**Comment by vitorbaptista** [comment]
FYI there're a few styling issues with IE. For example:

> win8.1 ie11.0
> Window 8.1 - IE 11.0
https://developer.microsoft.com/en-us/microsoft-edge/tools/screenshots/#http://opentrials.herokuapp.com

**Comment by vitorbaptista** [comment]
@smth Could you review this PR? I've made some tweaks, as explained in https://github.com/opentrials/opentrials/issues/40#issuecomment-203085734, but overall it should be just the implementation of your mockups. It's deployed to http://opentrials.herokuapp.com.

The styling issues in IE exist in your mockups as well. It would be great if you had some time to take a look.

**Comment by vitorbaptista** [comment]
It's now deployed at https://opentrials-staging-pr-42.herokuapp.com/

**Comment by smth** [comment]
I'm getting "Application Error".

**Comment by vitorbaptista** [comment]
@smth sorry, that's solved now

**Comment by smth** [comment]
Looks good. A few thoughts:
- (If we are not having a user login) a margin, or something needs to be added to the main menu, to correctly position it.
- Do we need the "registration date period" label? If so, could we have "registration start date" and registration end date" instead.
- Put the "Found x trials" in the [breadcrumb](http://opentrials.github.io/mockups/search-results.html), so "Search > Found x trials".

I haven't done any browser testing on these mockups, but for the issue above, I think we'll need to specify widths for the SVG https://github.com/opentrials/ot-scss/commit/5cd9f9c64e93e3eeda348a8792d5435c22589079

**Comment by pwalsh** [comment]
@smth user login will come very soon, so we can leave it

**Comment by vitorbaptista** [comment]
Thanks, @smth. I've implemented your suggestions and everything is looking fine. Merging this :+1:

**Pull request merged**
