### PR TITLE
[#313] Improve search input placeholder

### LINKED ISSUE #313: Improve placeholder for search input
Currently we simply use "Find a trial", but that's confusing. Should I put a trial title? Identifier? What about a condition? ClinicalTrials.gov uses `Example: "Heart Attack" AND "Los Angeles"`, which not only gives the example but also shows that you can use `AND` connectors and the use of double quotes. We can use something similar.

@benmeg thoughts?

### PR DESCRIPTION
**Pull request by vitorbaptista**
Same as with #314, this only changes the text, so assigning this to you, @benmeg. You can see the new text at https://ot-explorer-next-pr-318.herokuapp.com/

Fixes #313

### CODE REVIEW

**Comment by vitorbaptista** [comment]
@benmeg I'm merging this just to test during our user testing session. Please feel free to suggest improvements to the text.

**Comment by benmeg** [comment]
Currently the text is:

> Find a trial by title or other characteristics (e.g. breast cancer)

A few alternatives:

- Find a trial by title, NCTID, or other keywords (e.g. breast cancer)
- Example: "Heart Attack" AND "Los Angeles" (Vitor's suggestion - copying ClinicalTrials.gov)
- Find a trial by title, NCTID, or keywords - e.g. "back pain" AND relaxation (trying to combine the above two + using a shorter example that still demonstrates boolean operators and quotes)

**Comment by nightsh** [comment]
@benmeg this might be related to #288, I'll be working on it later this week. But we need to talk a bit about some implementation specifics, probably on the mentioned issue? Please give me a nudge if I'll forget about it :-)

**Comment by vitorbaptista** [comment]
@nightsh Right now, we support things like `AND` and `OR`, and quoting, so this doesn't depend on #288. I'll change the text slightly as per @benmeg suggestions, so no need to worry with this issue :+1:

**Comment by vitorbaptista** [comment]
Changed the text to `Find trial by title, identifier or other keywords (e.g. "heart attack")`. I would've liked to add an example with `AND`, but the text got too big and started disappearing on mobile screens.

**Pull request merged**
