### PR TITLE
[#92] Rename "Persons" to "People"

### LINKED ISSUE #92: Rename "persons"?
Maybe to [Sponsors/Collaborators](https://clinicaltrials.gov/ct2/help/sponsorandcollaborators) or just "People"

### PR DESCRIPTION
**Pull request by vitorbaptista**
We've just renamed it in the UI, so the API still returns "persons". It's
somewhat inconsistent, but it's easier to work with regular plurals in code.

Fixes #92

### CODE REVIEW

**Comment by roll** [comment]
@vitorbaptista 
I've found another on:
```
views/persons-details.html
5:  <h2>Person description</h2>
7:    <li>{{ person.name }}</li>
```

**Comment by vitorbaptista** [comment]
@roll That's correct, as it's for a single person

**Comment by roll** [comment]
sorry my bad

:+1:

**Comment by vitorbaptista** [comment]
No worries, it shows that you've been doing thorough reviews :+1:

**Pull request merged**
