### PR TITLE
Feature/contribute data

### LINKED ISSUE #69: Interfaces to add data
# Description

Requires https://github.com/opentrials/opentrials/issues/68

Users can add data to the system. This data can be associated with a known trial, or not. See here for data structure info and more general context https://github.com/opentrials/opentrials/issues/68

# Tasks

- [x] Implement interactions on trial detail pages
- [x] Add a new page "Contribute Data" that implements the upload data form, without the context of a trial (don't worry if design is not perfect)
- [x] Above two tasks require success/fail interactions in front of user:
  - [x] Can add if not authed
  - [x] Feedback if file upload failed
  - [x] Feedback if file upload successful
- [x] Add a link to the "Contribute Data" page from the footer
- [x] functional tests as relevant

### PR DESCRIPTION
**Pull request by vitorbaptista**
Add `/contribute-data` page where users (logged in or not) can upload documents related to a trial or not. The data is uploaded to S3 and its metadata saved to the database. Currently, there's no interface to see what was uploaded. In #70 and #71, we'll build a moderation interface for curators to approve/reject the files.

Fixes #69. Issue #68 won't be fixed, as the data goes to the Explorer database, not the API's.

### CODE REVIEW

**Comment by pwalsh** [comment]
@vitorbaptista shouldn't metadata go straight to the warehouse, for (potential processing there)?

**Comment by vitorbaptista** [comment]
@pwalsh I added it in the Explorer database because the users/roles are already in this DB and #70 would be created on top of it as well.

If we were to send the data contributions directly to the warehouse, then the moderation should be done over there as well IMHO, possibly as a separate codebase.

**Comment by pwalsh** [comment]
@vitorbaptista no worries. i guess we can decide at a later date if there is a need for it.

**Comment by roll** [comment]
For `processors` there is no difference from which database get data to process. But if `explorer` write data to `warehouse` any `warehouse` migration or outage could break `explorer`.

**Comment by roll** [comment]
@vitorbaptista 
I'll review on Monday. Feel free to merge if it will be blocking - I'll ccould heck it merged.

**Comment by roll** [comment]
@vitorbaptista 
It looks like I have problem with s3 settings. Trying to fix it. 

But error message not really descriptive:
- bad upload finishes with `{"statusCode":400,"error":"Bad Request","message":"child \"response\" fails because [\"response\" is not allowed to be empty]","validation":{"source":"payload","keys":["response"]}}` in a browser
- and `
160517/164338.618, [response], http://localhost:5000: post /contribute-data {"trial_id":"2b1c993b-44bd-42d7-b399-9649d8974a1a","redirectTo":"/trials/2b1c993b-44bd-42d7-b399-9649d8974a1a"} 400 (20ms)` in logs

**Comment by roll** [comment]
@vitorbaptista 
So a scenario:
- go to http://localhost:5000/contribute-data
- select and upload file with size lesser than
- get `{"statusCode":400,"error":"Bad Request","message":"child \"response\" fails because [\"response\" is not allowed to be empty]","validation":{"source":"payload","keys":["response"]}}` and no logged error in console

I think problem with my setup but I suppose we need to add some error logging here.

**Pull request merged**
